language: go

go:
  - "1.11.x"

# Clean and don't fail
install:
  - rm -rf public || exit 0

before_script:
  - gem install asciidoctor
  - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.tar.gz -O /tmp/hugo.tar.gz
  - wget https://github.com/bmuschko/link-verifier/releases/download/v0.6.2/link-verifier-0.6.2-linux-amd64.tar.gz -O /tmp/link-verifier.tar.gz
  - tar -xvf /tmp/hugo.tar.gz
  - tar -xvf /tmp/link-verifier.tar.gz
  - export PATH=$PATH:$PWD/hugo/:$PWD/link-verifier/

# Build the website
script:
  - ./link-verifier -dirs layouts -include=*.html -timeout 90
  - ./hugo
  - echo automatedascent.com >> public/CNAME

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  on:
    branch: master